# Generated by Django 5.1.2 on 2024-11-19 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membeli',
            name='id_obat',
        ),
        migrations.CreateModel(
            name='DetailMemasok',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='idDetailPembelian')),
                ('idMemasok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaran2.memasok', verbose_name='idMembeli')),
                ('id_obat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaran2.obat', verbose_name='Obat')),
            ],
            options={
                'verbose_name': 'DetailPembelian',
                'verbose_name_plural': 'DetailPembelians',
            },
        ),
        migrations.CreateModel(
            name='DetailPembelian',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='idDetailPembelian')),
                ('idMembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaran2.membeli', verbose_name='idMembeli')),
                ('id_obat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pembayaran2.obat', verbose_name='Obat')),
            ],
            options={
                'verbose_name': 'DetailPembelian',
                'verbose_name_plural': 'DetailPembelians',
            },
        ),
    ]
